const fs = require("fs");

async function autoRepair(problems) {

    const repaired = [];

    for (const problem of problems) {

        // Пустой JS-файл
        if (problem.type === "empty_file") {

            if (problem.file.endsWith(".js")) {

                fs.writeFileSync(
                    problem.file,
`// Auto-generated by Anna OS

module.exports = {};
`
                );

                repaired.push({
                    file: problem.file,
                    action: "created module"
                });

            }

        }

        // Отсутствующий require
        if (problem.type === "missing_module") {

            fs.writeFileSync(
                problem.target,
`// Auto-generated by Anna OS

module.exports = {};
`
            );

            repaired.push({
                file: problem.target,
                action: "created missing module"
            });

        }

    }

    return repaired;

}

module.exports = {
    autoRepair
};